# Generated by Django 4.2 on 2024-04-08 17:29

import apps.main.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('article', 'Статья'), ('video', 'Видео'), ('presentation', 'Презентация')], max_length=20, verbose_name='Тип')),
                ('title', models.CharField(max_length=1024, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to=apps.main.utils.get_material_upload_path, verbose_name='Изображение')),
                ('content', martor.models.MartorField(blank=True, null=True, verbose_name='Контент')),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'mkv'])], verbose_name='Видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('key_words', models.TextField(help_text='Слова перечисляются через запятую', verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(upload_to=apps.main.utils.get_slide_upload_path, verbose_name='Слайд')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ('order',),
            },
        ),
    ]
